# Generated by Django 2.2.7 on 2019-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=32)),
                ('nascimento', models.DateField()),
                ('email', models.CharField(max_length=64)),
                ('foto', models.BinaryField()),
            ],
        ),
    ]
