# Generated by Django 2.2.7 on 2019-11-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endereco_telefone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefone',
            unique_together={('id', 'id_pessoa')},
        ),
    ]
