# Generated by Django 2.2.7 on 2019-12-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191124_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='api.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='api.Pessoa'),
        ),
    ]
